# Generated by Django 3.2.8 on 2022-08-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='film',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
